# Generated by Django 2.2.10 on 2020-02-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_text', models.TextField()),
                ('embedded_video_url', models.URLField()),
                ('translated_title', models.CharField(max_length=200)),
                ('translated_text', models.TextField()),
                ('publication_date', models.DateTimeField(verbose_name='date published')),
                ('last_updated_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
