# Generated by Django 2.2.10 on 2020-02-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200211_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_after_video',
            field=models.TextField(default=''),
        ),
    ]
