# Generated by Django 2.2.10 on 2020-02-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_article_text_after_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='date_published'),
        ),
    ]
