# Generated by Django 2.2.10 on 2020-02-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200211_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedded_video_title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
