# Generated by Django 2.2.10 on 2020-02-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_article_embedded_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='embedded_video_title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='translated_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='translated_title',
        ),
        migrations.AddField(
            model_name='article',
            name='article_language',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.CreateModel(
            name='TranslatedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_language', models.CharField(max_length=2)),
                ('article_title', models.CharField(max_length=200)),
                ('article_text', models.TextField()),
                ('embedded_video_url', models.URLField()),
                ('text_after_video', models.TextField(default='')),
                ('keep_top_position', models.BooleanField(default=False)),
                ('publication_datetime', models.DateTimeField(auto_now=True, verbose_name='date_published')),
                ('last_updated_datetime', models.DateTimeField(auto_now=True, verbose_name='last_updated')),
                ('article', models.ForeignKey(on_delete=models.CASCADE, related_name='translations', to='website.Article')),
            ],
        ),
    ]
