# Generated by Django 2.2.10 on 2020-02-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text_after_video',
            new_name='text_after_media',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='high_res1',
            new_name='high_res',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='low_res1',
            new_name='low_res',
        ),
        migrations.RemoveField(
            model_name='images',
            name='high_res2',
        ),
        migrations.RemoveField(
            model_name='images',
            name='low_res2',
        ),
    ]
