# Generated by Django 2.2.10 on 2020-02-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200213_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='translatedarticle',
            old_name='article_language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='translatedarticle',
            old_name='article_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='translatedarticle',
            old_name='article_title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default='', max_length=360),
        ),
        migrations.AddField(
            model_name='translatedarticle',
            name='abstract',
            field=models.CharField(default='', max_length=360),
        ),
    ]
