# Generated by Django 2.2.10 on 2020-02-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200228_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='embedded_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_after_media',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='translatedarticle',
            name='embedded_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='translatedarticle',
            name='text_after_video',
            field=models.TextField(blank=True, default=''),
        ),
    ]
