# Generated by Django 2.2.10 on 2020-03-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200302_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedarticle',
            name='slug',
            field=models.SlugField(default='lorem'),
            preserve_default=False,
        ),
    ]
