# Generated by Django 2.2.10 on 2020-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_translatedarticle_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_info_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translatedarticle',
            name='is_info_page',
            field=models.BooleanField(default=False),
        ),
    ]
