# Generated by Django 2.2.10 on 2020-03-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200306_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='translatedarticle',
            name='abstract',
            field=models.TextField(blank=True),
        ),
    ]
