# Generated by Django 2.2.10 on 2020-03-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200314_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.Article'),
        ),
        migrations.AlterField(
            model_name='translatedarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='website.Article'),
        ),
    ]
