# Generated by Django 2.2.10 on 2020-05-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200319_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='high_res',
        ),
        migrations.RemoveField(
            model_name='images',
            name='low_res',
        ),
        migrations.AddField(
            model_name='images',
            name='high_res_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='images',
            name='low_res_url',
            field=models.URLField(blank=True),
        ),
    ]
